-- ================================================================
-- SK Driving — Affiliate / Referral Schema
-- Run in: Supabase Dashboard → SQL Editor → New Query → Run
--
-- Model: a user enrols as an affiliate and gets a unique referral
-- `code`. Visitors arriving with ?ref=CODE are cookie-tagged. When a
-- tagged user signs up a `referrals` row is created; when they pay,
-- the Yoco webhook records an `affiliate_commissions` row (a % of the
-- payment) and bumps the affiliate's running totals.
-- ================================================================

-- 1. AFFILIATES (one per user)
create table if not exists public.affiliates (
  id                uuid primary key default gen_random_uuid(),
  user_id           uuid not null references auth.users(id) on delete cascade,
  code              text not null unique,           -- short referral code, e.g. 'SK7F3A2K'
  commission_rate   numeric(4,3) not null default 0.200,  -- 0.200 = 20%
  status            text not null default 'active', -- 'active' | 'suspended'
  total_earned_cents int not null default 0,        -- lifetime commission earned
  total_paid_cents   int not null default 0,        -- lifetime paid out to affiliate
  created_at        timestamptz not null default now(),
  unique (user_id)
);

-- 2. REFERRALS (one referrer per referred user)
create table if not exists public.referrals (
  id                uuid primary key default gen_random_uuid(),
  affiliate_id      uuid not null references public.affiliates(id) on delete cascade,
  referred_user_id  uuid not null references auth.users(id) on delete cascade,
  code              text not null,                  -- code used at signup
  status            text not null default 'signed_up', -- 'signed_up' | 'converted'
  converted_at      timestamptz,
  created_at        timestamptz not null default now(),
  unique (referred_user_id)
);

-- 3. AFFILIATE COMMISSIONS (one per qualifying payment)
create table if not exists public.affiliate_commissions (
  id                uuid primary key default gen_random_uuid(),
  affiliate_id      uuid not null references public.affiliates(id) on delete cascade,
  referral_id       uuid references public.referrals(id) on delete set null,
  referred_user_id  uuid references auth.users(id) on delete set null,
  yoco_payment_id   text unique,                    -- prevents double-crediting a payment
  amount_cents      int  not null,                  -- the payment amount
  commission_cents  int  not null,                  -- what the affiliate earns
  status            text not null default 'pending', -- 'pending' | 'approved' | 'paid'
  created_at        timestamptz not null default now()
);

-- 4. AFFILIATE CLICKS (lightweight analytics)
create table if not exists public.affiliate_clicks (
  id            bigint generated by default as identity primary key,
  affiliate_id  uuid references public.affiliates(id) on delete cascade,
  code          text not null,
  created_at    timestamptz not null default now()
);

-- ── INDEXES ─────────────────────────────────────────────────────
create index if not exists idx_affiliates_user        on public.affiliates(user_id);
create index if not exists idx_affiliates_code         on public.affiliates(code);
create index if not exists idx_referrals_affiliate     on public.referrals(affiliate_id);
create index if not exists idx_referrals_user          on public.referrals(referred_user_id);
create index if not exists idx_commissions_affiliate   on public.affiliate_commissions(affiliate_id);
create index if not exists idx_clicks_affiliate        on public.affiliate_clicks(affiliate_id);

-- ── ROW-LEVEL SECURITY ──────────────────────────────────────────
-- Reads are scoped to the owning affiliate. All writes happen via the
-- service-role key in API routes / the Yoco webhook (which bypass RLS).
alter table public.affiliates           enable row level security;
alter table public.referrals            enable row level security;
alter table public.affiliate_commissions enable row level security;
alter table public.affiliate_clicks     enable row level security;

do $$ begin
  drop policy if exists "affiliates_own_read"   on public.affiliates;
  drop policy if exists "referrals_own_read"    on public.referrals;
  drop policy if exists "commissions_own_read"  on public.affiliate_commissions;
  drop policy if exists "clicks_own_read"       on public.affiliate_clicks;

  -- Affiliate can read their own affiliate row
  create policy "affiliates_own_read"
    on public.affiliates for select to authenticated
    using (auth.uid() = user_id);

  -- Affiliate can read referrals that belong to their affiliate account
  create policy "referrals_own_read"
    on public.referrals for select to authenticated
    using (affiliate_id in (select id from public.affiliates where user_id = auth.uid()));

  -- Affiliate can read their own commissions
  create policy "commissions_own_read"
    on public.affiliate_commissions for select to authenticated
    using (affiliate_id in (select id from public.affiliates where user_id = auth.uid()));

  -- Affiliate can read their own click log
  create policy "clicks_own_read"
    on public.affiliate_clicks for select to authenticated
    using (affiliate_id in (select id from public.affiliates where user_id = auth.uid()));
end $$;
