-- ================================================================
-- SK Driving — Quiz Sessions (server-side free-preview timer)
-- Run in: Supabase Dashboard → SQL Editor → New Query → Run
--
-- Records when a free user first started a given test so the 3-minute
-- preview is enforced server-side and can't be reset by reloading or
-- tampering with the client timer. One row per (identity, course, test):
--   - logged-in users are keyed by user_id
--   - anonymous users are keyed by session_key (an httpOnly cookie uuid)
-- Premium users are never timed, so they get no rows here.
-- ================================================================

create table if not exists public.quiz_sessions (
  id           bigint generated by default as identity primary key,
  user_id      uuid references auth.users(id) on delete cascade,
  session_key  text,                       -- cookie uuid for anonymous users
  course_id    bigint not null,
  test_number  int    not null,
  started_at   timestamptz not null default now(),
  created_at   timestamptz not null default now()
);

-- One free-preview window per identity + test. Partial unique indexes so
-- user_id and session_key are each unique per (course, test) independently.
create unique index if not exists uniq_quiz_sessions_user
  on public.quiz_sessions (user_id, course_id, test_number)
  where user_id is not null;

create unique index if not exists uniq_quiz_sessions_anon
  on public.quiz_sessions (session_key, course_id, test_number)
  where session_key is not null;

-- RLS on, no policies: only the service-role key (used by the
-- /api/quiz/session route) may read or write these rows.
alter table public.quiz_sessions enable row level security;
