-- ================================================================
-- SK Driving — Affiliate Programme (activate, 30% + bank details)
-- Run in: Supabase Dashboard → SQL Editor → New Query → Run
--
-- Affiliates self-register (name, email, bank details), get a unique referral
-- link, and earn 30% of every successful card payment made through their link.
-- Payouts are made to their bank account weekly (Mondays). Idempotent.
-- ================================================================

-- 1. AFFILIATES (one per user account)
create table if not exists public.affiliates (
  id                 uuid primary key default gen_random_uuid(),
  user_id            uuid not null references auth.users(id) on delete cascade,
  code               text not null unique,
  first_name         text,
  last_name          text,
  email              text,
  bank_account_name  text,                       -- account holder name
  bank_name          text,
  account_number     text,
  account_type       text,                       -- 'cheque' | 'savings'
  commission_rate    numeric(4,3) not null default 0.300,  -- 30%
  status             text not null default 'active',       -- 'active' | 'suspended'
  total_earned_cents int not null default 0,
  total_paid_cents   int not null default 0,
  created_at         timestamptz not null default now(),
  unique (user_id)
);

-- Add any missing columns if an earlier affiliates table already existed.
alter table public.affiliates add column if not exists first_name        text;
alter table public.affiliates add column if not exists last_name         text;
alter table public.affiliates add column if not exists email             text;
alter table public.affiliates add column if not exists bank_account_name text;
alter table public.affiliates add column if not exists bank_name         text;
alter table public.affiliates add column if not exists account_number    text;
alter table public.affiliates add column if not exists account_type      text;

-- Everyone earns 30%.
alter table public.affiliates alter column commission_rate set default 0.300;
update public.affiliates set commission_rate = 0.300 where commission_rate <> 0.300;

-- 2. COMMISSIONS (one per successful payment)
create table if not exists public.affiliate_commissions (
  id               uuid primary key default gen_random_uuid(),
  affiliate_id     uuid not null references public.affiliates(id) on delete cascade,
  yoco_payment_id  text unique,                  -- prevents double-crediting a payment
  yoco_checkout_id text,
  amount_cents     int  not null,                -- the payment amount
  commission_cents int  not null,                -- 30% earned
  status           text not null default 'pending',  -- 'pending' | 'paid'
  created_at       timestamptz not null default now()
);

-- 3. CLICKS (lightweight analytics)
create table if not exists public.affiliate_clicks (
  id           bigint generated by default as identity primary key,
  affiliate_id uuid references public.affiliates(id) on delete cascade,
  code         text not null,
  created_at   timestamptz not null default now()
);

-- INDEXES
create index if not exists idx_affiliates_user      on public.affiliates(user_id);
create index if not exists idx_affiliates_code       on public.affiliates(code);
create index if not exists idx_aff_comm_affiliate    on public.affiliate_commissions(affiliate_id);
create index if not exists idx_aff_clicks_affiliate  on public.affiliate_clicks(affiliate_id);

-- RLS — affiliates read only their own rows; all writes via service role.
alter table public.affiliates           enable row level security;
alter table public.affiliate_commissions enable row level security;
alter table public.affiliate_clicks     enable row level security;

do $$ begin
  drop policy if exists "affiliates_own_read"  on public.affiliates;
  drop policy if exists "aff_comm_own_read"    on public.affiliate_commissions;
  drop policy if exists "aff_clicks_own_read"  on public.affiliate_clicks;

  create policy "affiliates_own_read"
    on public.affiliates for select to authenticated
    using (auth.uid() = user_id);

  create policy "aff_comm_own_read"
    on public.affiliate_commissions for select to authenticated
    using (affiliate_id in (select id from public.affiliates where user_id = auth.uid()));

  create policy "aff_clicks_own_read"
    on public.affiliate_clicks for select to authenticated
    using (affiliate_id in (select id from public.affiliates where user_id = auth.uid()));
end $$;
