/**
 * Seed script — inserts Code 8 Test 2 questions into Supabase.
 * Run once:  node scripts/seed-test2.mjs
 */

const SUPABASE_URL = 'https://wzqgjzqylkbwyvzyzywu.supabase.co'
const ANON_KEY     = process.env.SUPABASE_SERVICE_ROLE_KEY ?? ''

// Image base path served from Next.js public folder
const IMG = (file) => `/images/code8/test2/${file}`

// ── 30 Rules of the Road questions ──────────────────────────────────────────
const rulesQuestions = [
  {
    question: 'If you want to turn left with your vehicle, you must...',
    option_a: 'Slow down completely, stop, and then turn',
    option_b: 'Give the necessary signal in good time',
    option_c: 'First move to the right to enable you to turn left easily',
    correct_answer: 'B',
  },
  {
    question: 'Where may you legally stop with your vehicle?',
    option_a: '4m from a tunnel',
    option_b: '5m from a pedestrian crossing',
    option_c: '6m from a railway crossing',
    correct_answer: 'B',
  },
  {
    question: 'When are you allowed to drive your vehicle on the right-hand side of a road with traffic moving in both directions?',
    option_a: 'When a traffic officer directs you to do so',
    option_b: 'When you switch the emergency lights of your vehicle on',
    option_c: 'Under no circumstances',
    correct_answer: 'A',
  },
  {
    question: 'How far may you park from the left edge of a roadway outside an urban area?',
    option_a: 'Not more than 450mm from the edge of the roadway',
    option_b: 'Not more than 1m from the edge of the roadway',
    option_c: 'A vehicle may not park on a public road unless in a parking bay',
    correct_answer: 'C',
  },
  {
    question: 'You may not...\n(i) Run the engine unattended\n(ii) Use your vehicle without a cap on the fuel tank\n(iii) Spin the wheels of your vehicle when pulling off\n\nSELECT THE CORRECT COMBINATION',
    option_a: '(ii) only is correct',
    option_b: '(i) only is correct',
    option_c: 'All of the above are correct',
    correct_answer: 'C',
  },
  {
    question: 'The only instance where you may stop on a freeway is...',
    option_a: 'To obey a road traffic sign',
    option_b: 'For a rest during a tiring journey',
    option_c: 'To pick up hitchhikers',
    correct_answer: 'A',
  },
  {
    question: 'If you want to change lanes you must...',
    option_a: 'Switch on your indicator and change lanes immediately',
    option_b: 'Apply the brakes lightly and then change lanes',
    option_c: 'Give the necessary signal and, after checking for other traffic, change lanes',
    correct_answer: 'C',
  },
  {
    question: 'How far behind a vehicle must the warning triangle be placed if your vehicle breaks down?',
    option_a: 'At least 45m',
    option_b: 'At least 10m',
    option_c: 'At least 100m',
    correct_answer: 'A',
  },
  {
    question: 'When do you have the right of way?\n(i) When you are within a traffic circle\n(ii) When you have stopped first at a four-way stop\n(iii) When you want to turn right at an intersection on a two-way road\n\nSELECT THE CORRECT COMBINATION',
    option_a: '(i) and (ii) only are correct',
    option_b: 'All of the above are correct',
    option_c: '(i) only is correct',
    correct_answer: 'A',
  },
  {
    question: 'If you come to a traffic signal and the red light is flashing, you must...',
    option_a: 'Stop and proceed only if it is safe to do so',
    option_b: 'Look out for a roadblock as the light indicates a police stop',
    option_c: 'Stop and wait for the light to change to green before going',
    correct_answer: 'A',
  },
  {
    question: 'The use of a temporary sign implies that for some reason...',
    option_a: 'The rules of the road do not apply',
    option_b: 'Circumstances on the roadway are not normal',
    option_c: 'Traffic has to move slowly',
    correct_answer: 'B',
  },
  {
    question: 'A person driving a vehicle on a public road may...',
    option_a: 'Leave a vehicle unattended without applying its service brake to prevent it from moving',
    option_b: 'Leave a vehicle unattended without applying its parking brake to prevent it from moving from the position in which it was left',
    option_c: 'Not leave a vehicle unattended without applying its parking brake to prevent it from moving',
    correct_answer: 'C',
  },
  {
    question: 'In a light motor vehicle, the load should not project more than...',
    option_a: '2.6m',
    option_b: '4.3m high',
    option_c: 'Half of your vehicle\'s height',
    correct_answer: 'B',
  },
  {
    question: 'A safe following distance means that if the vehicle in front of you suddenly stops, you could...',
    option_a: 'Swerve and pass',
    option_b: 'Stop without swerving',
    option_c: 'Swerve and stop next to it',
    correct_answer: 'B',
  },
  {
    question: 'What colour and size must flags be to indicate load projections on a vehicle on a public road?',
    option_a: 'They may be any colour as long as they are visible',
    option_b: 'They must be red and at least 300mm x 300mm',
    option_c: 'They can be any size as long as they are red',
    correct_answer: 'B',
  },
  {
    question: 'The last action you must take before moving to another lane is to...',
    option_a: 'Look in the rear-view mirror',
    option_b: 'Check the blind spot',
    option_c: 'Switch on your indicator',
    correct_answer: 'B',
  },
  {
    question: 'When a motor vehicle is standing still, what must the driver do to ensure the vehicle does not move?',
    option_a: 'The parking brake must be applied',
    option_b: 'The gear lever must be put in the neutral position',
    option_c: 'The driver must hold the service brake',
    correct_answer: 'A',
  },
  {
    question: 'What is the function of a clutch?',
    option_a: 'It is used to disconnect the engine from the transmission',
    option_b: 'It is used to freewheel down a hill',
    option_c: 'It is used to reduce the speed of a vehicle',
    correct_answer: 'A',
  },
  {
    question: 'When may a driver disobey a rule of the road?',
    option_a: 'Only when directed to do so by a traffic officer',
    option_b: 'If you are driving in an emergency situation',
    option_c: 'Under no circumstances',
    correct_answer: 'A',
  },
  {
    question: 'When driving a motor vehicle, what is the minimum safe following distance to maintain when following another vehicle?',
    option_a: 'Five metres at 100km/h',
    option_b: 'A distance determined by means of the two-second rule',
    option_c: 'A driver may drive as close as possible so that overtaking will be easier',
    correct_answer: 'B',
  },
  {
    question: 'You may not drive into an intersection when...',
    option_a: 'There is not enough space in the intersection to clear it without blocking other traffic',
    option_b: 'The traffic signal is yellow and you are already in the intersection',
    option_c: 'The vehicle in front of you wants to turn right and the road is wide enough to pass on the left side',
    correct_answer: 'A',
  },
  {
    question: 'When you are involved in an accident you...\n(i) Must immediately stop your vehicle\n(ii) Must determine the damage to the vehicles\n(iii) May refuse to give your name and address to anyone except the police\n\nSELECT THE CORRECT COMBINATION',
    option_a: '(ii) only is correct',
    option_b: '(i) and (ii) only are correct',
    option_c: 'All of the above are correct',
    correct_answer: 'C',
  },
  {
    question: 'When you are involved in an accident you...\n(i) Must immediately stop your vehicle\n(ii) Must see if someone is injured\n(iii) May use a bit of alcohol for the shock\n\nSELECT THE CORRECT COMBINATION',
    option_a: '(i) and (ii) only are correct',
    option_b: '(ii) only is correct',
    option_c: 'All of the above are correct',
    correct_answer: 'A',
  },
  {
    question: 'Whilst the vehicle is in motion, a driver may...',
    option_a: 'Hold a cell phone provided the driver keeps at least one hand on the steering wheel',
    option_b: 'Type an SMS',
    option_c: 'Not hold a cell phone with any part of the body',
    correct_answer: 'C',
  },
  {
    question: 'What is important with regard to the hooter of your vehicle?',
    option_a: 'Someone must hear it from a distance of at least 50m',
    option_b: 'The tone and pitch of the sound may not change',
    option_c: 'You may use it to get the attention of someone you would like to offer a lift',
    correct_answer: 'B',
  },
  {
    question: 'You must stop your vehicle...\n(i) On a public road at the signal of a person herding sheep\n(ii) On a freeway when directed to do so by a traffic officer\n(iii) On any road to avoid an accident\n\nSELECT THE CORRECT COMBINATION',
    option_a: 'Only (iii) is correct',
    option_b: 'Only (ii) and (iii) are correct',
    option_c: 'All of the above are correct',
    correct_answer: 'C',
  },
  {
    question: 'What are the requirements regarding a vehicle being operated with excessive noise?',
    option_a: 'There are no requirements with regard to excessive noise on a vehicle',
    option_b: 'Excessive noise is acceptable during festive periods such as Christmas and New Year',
    option_c: 'No person shall operate a vehicle on a public road that causes any excessive noise',
    correct_answer: 'C',
  },
  {
    question: 'What is the duty of a driver when driving on a public road that has been divided into two or more roadways?',
    option_a: 'You may drive on any part of the roadway',
    option_b: 'You are allowed to drive on any part of the roadway after sunset, or when there is no other traffic on the road',
    option_c: 'Drive on the left-hand roadway unless directed or shown to do so by a traffic officer or traffic sign',
    correct_answer: 'C',
  },
  {
    question: 'When you drive...',
    option_a: 'You must wear shoes with rubber soles',
    option_b: 'Your vision of the road and the traffic must be unobstructed',
    option_c: 'You must have both hands on the steering wheel at all times',
    correct_answer: 'B',
  },
  {
    question: 'You may cross or enter a public road...',
    option_a: 'If the road is clear of traffic for a sufficient distance and it can be done without obstructing traffic',
    option_b: 'If the road is clear of traffic for a short distance',
    option_c: 'In any manner as long as you use your indicators in time',
    correct_answer: 'A',
  },
]

// ── 30 Road Signs / Vehicle Controls questions ──────────────────────────────
const signsQuestions = [
  {
    question: 'What is this road worker signalling drivers to do?',
    option_a: 'To proceed with caution',
    option_b: 'To stop',
    option_c: 'To turn back',
    correct_answer: 'B',
    image_ref: '2c8.1.img.png',
  },
  {
    question: 'Which control is used to check the vehicles behind?',
    option_a: '4',
    option_b: '11',
    option_c: '3',
    correct_answer: 'B',
    image_ref: '2c8.2.img.png',
  },
  {
    question: 'To accelerate your vehicle you must use number...',
    option_a: '6',
    option_b: '10',
    option_c: '8',
    correct_answer: 'B',
    image_ref: '2c8.3.img.png',
  },
  {
    question: 'This road sign warns you of...',
    option_a: 'Heavy motor vehicles that may be moving slowly on a declining slope ahead',
    option_b: 'A stationary heavy motor vehicle ahead',
    option_c: 'An accident ahead involving a light and a heavy motor vehicle',
    correct_answer: 'A',
    image_ref: '2c8.4.img.png',
  },
  {
    question: 'To ensure that your parked vehicle does not move, use number...',
    option_a: '8',
    option_b: '7',
    option_c: '9',
    correct_answer: 'B',
    image_ref: '2c8.5.img.png',
  },
  {
    question: 'Which sign indicates you must turn right?',
    option_a: 'A',
    option_b: 'C',
    option_c: 'B',
    correct_answer: 'B',
    image_ref: '2c8.6.img.png',
  },
  {
    question: 'Which is the correct statement regarding this pedestrian signal?',
    option_a: 'When the red man is showing, pedestrians have priority',
    option_b: 'When the green man is showing, pedestrians may cross; when the red man is showing, pedestrians may not cross',
    option_c: 'When the green man is showing, pedestrians should run across as fast as they can',
    correct_answer: 'B',
    image_ref: '2c8.7.png',
  },
  {
    question: 'To indicate that you are going to turn, you must use number...',
    option_a: '11',
    option_b: '3',
    option_c: '5',
    correct_answer: 'C',
    image_ref: '2c8.8.img.png',
  },
  {
    question: 'What is the purpose of this information sign?',
    option_a: 'To count down the distance to the next town',
    option_b: 'To count down the distance to the next exit on a freeway',
    option_c: 'To count down the distance to the next on-ramp to a freeway',
    correct_answer: 'B',
    image_ref: '2c8.9.img.png',
  },
  {
    question: 'What does this road sign indicate?',
    option_a: 'A parking spot reserved for buses',
    option_b: 'A pick-up or drop-off area reserved for a bus belonging to a specific company or organisation',
    option_c: 'A lane reserved for a vehicle belonging to a specific company or organisation',
    correct_answer: 'B',
    image_ref: '2c8.10.img.png',
  },
  {
    question: 'What does this road sign inform drivers of?',
    option_a: 'An exit ahead on a freeway, shown in good time',
    option_b: 'An on-ramp to a freeway shown in good time',
    option_c: 'Turn left to enter a freeway',
    correct_answer: 'A',
    image_ref: '2c8.11.img.png',
  },
  {
    question: 'What is this road sign called?',
    option_a: 'An alternative route marker',
    option_b: 'A map-type trailblazer',
    option_c: 'An advance trailblazer',
    correct_answer: 'C',
    image_ref: '2c8.12.img.png',
  },
  {
    question: 'The appropriate reaction to this sign would be to...',
    option_a: 'Be on the lookout for vehicles changing lanes, especially from the left',
    option_b: 'Keep left',
    option_c: 'Turn right at the next intersection',
    correct_answer: 'A',
    image_ref: '2c8.13.img.png',
  },
  {
    question: 'When the traffic signal is red and the green arrow flashes to the right, it means...',
    option_a: 'If you want to turn right, you may do so',
    option_b: 'Only pedestrians may walk',
    option_c: 'All traffic must turn right',
    correct_answer: 'A',
    image_ref: '2c8.14.img.png',
  },
  {
    question: 'This sign warns a driver that...',
    option_a: 'A side road junction from the right is ahead',
    option_b: 'A skew T-junction is ahead',
    option_c: 'A T-junction is ahead',
    correct_answer: 'A',
    image_ref: '2c8.15.img.png',
  },
  {
    question: 'When may you stop in front of this sign?',
    option_a: 'Only when picking up passengers',
    option_b: 'Only when you want to look at the scenery',
    option_c: 'Never',
    correct_answer: 'C',
    image_ref: '2c8.16.img.jfif',
  },
  {
    question: 'Does this road marking have the same purpose as a stop sign?',
    option_a: 'True',
    option_b: 'False',
    option_c: 'Only at night or in poor visibility',
    correct_answer: 'A',
    image_ref: '2c8.17.img.png',
  },
  {
    question: 'What does this sign prohibit?',
    option_a: 'It prohibits heavy motor vehicles from entering where the sign is displayed',
    option_b: 'It prohibits unauthorised vehicles from entering where the sign is displayed',
    option_c: 'It prevents all vehicles from entering where the sign is displayed',
    correct_answer: 'A',
    image_ref: '2c8.18.img.png',
  },
  {
    question: 'This road sign shows you that...',
    option_a: 'The road is a one-way road',
    option_b: 'Overtaking is prohibited for the next 2km',
    option_c: 'The road is narrow and cannot handle two motor cars side by side',
    correct_answer: 'B',
    image_ref: '2c8.19.img.png',
  },
  {
    question: 'When approaching this sign, the driver must...',
    option_a: 'Yield and carry on when it is safe to do so',
    option_b: 'Know that they are warned of a stop sign ahead',
    option_c: 'Stop behind the stop line and give right of way to vehicles from the right',
    correct_answer: 'B',
    image_ref: '2c8.20.img.png',
  },
  {
    question: 'This sign indicates...',
    option_a: 'The direction to a freeway',
    option_b: 'The presence of a bridge',
    option_c: 'That all traffic must turn right',
    correct_answer: 'A',
    image_ref: '2c8.21.img.png',
  },
  {
    question: 'What does this control sign indicate?',
    option_a: 'Turning left is prohibited',
    option_b: 'You should turn left',
    option_c: 'The road turning to the left is a one-way road',
    correct_answer: 'B',
    image_ref: '2c8.22.img.png',
  },
  {
    question: 'This road marking shows you a lane that...',
    option_a: 'Is reserved for aeroplanes',
    option_b: 'You may follow if you want to go to an airport',
    option_c: 'Is reserved for aircraft in an emergency',
    correct_answer: 'B',
    image_ref: '2c8.23.img.png',
  },
  {
    question: 'When you encounter this road marking, the correct reaction would be to...',
    option_a: 'Yield only to traffic from the right',
    option_b: 'Stop over the line and then proceed when it is safe to do so',
    option_c: 'Yield right of way to any vehicle which crosses the yield line before you',
    correct_answer: 'C',
    image_ref: '2c8.24.img.png',
  },
  {
    question: 'This sign shows you that...',
    option_a: 'The road ends ahead',
    option_b: 'Only cars may enter',
    option_c: 'There is a one-way road ahead',
    correct_answer: 'A',
    image_ref: '2c8.24.1.img.png',
  },
  {
    question: 'This road sign prohibits...',
    option_a: 'Cars from turning right at this point',
    option_b: 'Cars from turning right ahead',
    option_c: 'All vehicles from turning right',
    correct_answer: 'B',
    image_ref: '2c8.25.img.png',
  },
  {
    question: 'What does this road sign indicate?',
    option_a: 'That you do not have the right of way at the next intersection',
    option_b: 'That there is a danger ahead',
    option_c: 'That you have the right of way at the next intersection',
    correct_answer: 'C',
    image_ref: '2c8.26.img.png',
  },
  {
    question: 'Which control must you use when it is raining?',
    option_a: '2',
    option_b: '5',
    option_c: '1',
    correct_answer: 'B',
    image_ref: '2c8.27.img.png',
  },
  {
    question: 'This sign confirms...',
    option_a: 'How much toll you will have to pay',
    option_b: 'Which way all vehicles have to go',
    option_c: 'A toll road and an alternative route to avoid the toll',
    correct_answer: 'C',
    image_ref: '2c8.28.img.png',
  },
  {
    question: 'When seeing this sign you should know that...',
    option_a: 'There is a public phone ahead',
    option_b: 'There is an emergency phone 500m ahead on the road',
    option_c: 'There is no cell phone reception for the next 500m',
    correct_answer: 'B',
    image_ref: '2c8.29.img.png',
  },
]

// ── Build final rows ─────────────────────────────────────────────────────────
const rows = [
  ...rulesQuestions.map(q => ({
    course_id:      2,
    test_number:    2,
    question:       q.question,
    option_a:       q.option_a,
    option_b:       q.option_b,
    option_c:       q.option_c,
    correct_answer: q.correct_answer,
    image_url:      null,
    image_ref:      null,
  })),
  ...signsQuestions.map(q => ({
    course_id:      2,
    test_number:    2,
    question:       q.question,
    option_a:       q.option_a,
    option_b:       q.option_b,
    option_c:       q.option_c,
    correct_answer: q.correct_answer,
    image_url:      IMG(q.image_ref),
    image_ref:      q.image_ref,
  })),
]

// ── Insert ───────────────────────────────────────────────────────────────────
console.log(`Inserting ${rows.length} questions…`)

const res = await fetch(`${SUPABASE_URL}/rest/v1/quiz_questions`, {
  method:  'POST',
  headers: {
    'Content-Type':  'application/json',
    'apikey':        ANON_KEY,
    'Authorization': `Bearer ${ANON_KEY}`,
    'Prefer':        'return=minimal',
  },
  body: JSON.stringify(rows),
})

if (res.ok) {
  console.log(`✓ Inserted ${rows.length} questions successfully (status ${res.status})`)
} else {
  const text = await res.text()
  console.error(`✗ Insert failed (${res.status}):`, text)
}
