-- =================================================================
-- K53 Platform — Seed: Code 8 Test 1 Questions
-- Generated: 2026-05-14T16:13:14.981Z
-- Run in: Supabase Dashboard → SQL Editor → New Query
-- =================================================================

DO $$
DECLARE
  v_course_id bigint;
BEGIN
  -- Get the Code 8 course id
  SELECT id INTO v_course_id FROM courses WHERE code = 'code8';

  IF v_course_id IS NULL THEN
    RAISE EXCEPTION 'Course with code=code8 not found. Did you run schema.sql first?';
  END IF;

  -- Clear existing test 1 questions for this course (safe to re-run)
  DELETE FROM quiz_questions WHERE course_id = v_course_id AND test_number = 1;

  -- Insert all 62 questions
  INSERT INTO quiz_questions
    (course_id, test_number, question, option_a, option_b, option_c, correct_answer, image_url, image_ref)
  VALUES
    (v_course_id, 1, 'When seeing this sign the driver knows that he/she must...', 'keep in the left lane only', 'pass to the left of the obstacle on which the sign has been placed', 'Proceed on the left side of the road', 'B', 'https://wzqgjzqylkbwyvzyzywu.supabase.co/storage/v1/object/public/resources/code8/test1/c8.1.q1.img.png', 'c8.1.q1.img.png'),
    (v_course_id, 1, 'When this signal is illuminated it shows you that...', 'there is an unguarded railway crossing ahead', 'it is a traffic lane that vehicles may not enter', 'there is no throughway there', 'B', 'https://wzqgjzqylkbwyvzyzywu.supabase.co/storage/v1/object/public/resources/code8/test1/c81.q2.img.png', 'c81.q2.img.png'),
    (v_course_id, 1, 'When travelling on this secondary crossroad you...', 'only have to stop if traffic from the left or right is approaching', 'do not have right of way and you have to stop', 'have right of way', 'B', 'https://wzqgjzqylkbwyvzyzywu.supabase.co/storage/v1/object/public/resources/code8/test1/C81.q3.img.png', 'C81.q3.img.png'),
    (v_course_id, 1, 'This sign indicates to a driver that there is a freeway exit in ... ahead', '100 meters', '1 km', '10 meters', 'A', 'https://wzqgjzqylkbwyvzyzywu.supabase.co/storage/v1/object/public/resources/code8/test1/C81.q4.img.png', 'C81.q4.img.png'),
    (v_course_id, 1, 'Where can you find this direction sign', 'On the left-hand side of a freeway next to the off-ramp', 'On any freeway with multiple traffic lanes', 'On any ordinary road with more than one traffic lane', 'C', 'https://wzqgjzqylkbwyvzyzywu.supabase.co/storage/v1/object/public/resources/code8/test1/C81.q6.img.png', 'C81.q6.img.png'),
    (v_course_id, 1, 'This sign shows you that...', 'vehicles may overtake on the left side from there on', 'the people driving on the left side of the road must turn left', 'a lane is added to the left of a two-way roadway', 'C', 'https://wzqgjzqylkbwyvzyzywu.supabase.co/storage/v1/object/public/resources/code8/test1/C81.q7.img.png', 'C81.q7.img.png'),
    (v_course_id, 1, 'Where do you find this direction sign', 'On any public road indicating single exit lanes', 'Only in towns or suburbs', 'On any freeway indicating dedicated exit lanes', 'C', 'https://wzqgjzqylkbwyvzyzywu.supabase.co/storage/v1/object/public/resources/code8/test1/c8.1.q8.img.png', 'c8.1.q8.img.png'),
    (v_course_id, 1, 'What is this road sign used for', 'To indicate distances in km to the next town or suburb', 'To indicate exits that are close together in good time all leading to the same town', 'To indicate payable toll-pay fees on each route', 'B', 'https://wzqgjzqylkbwyvzyzywu.supabase.co/storage/v1/object/public/resources/code8/test1/c8.1.q9.img.png', 'c8.1.q9.img.png'),
    (v_course_id, 1, 'This road marking...', 'divides the road into two lanes', 'shows that overtaking is not allowed', 'it is only found in a parking area', 'A', 'https://wzqgjzqylkbwyvzyzywu.supabase.co/storage/v1/object/public/resources/code8/test1/c8.1.q10.img.png', 'c8.1.q10.img.png'),
    (v_course_id, 1, 'This signal indicates that...', 'this lane is for slow moving traffic only', 'you may drive there', 'this lane is for fast moving traffic only', 'B', 'https://wzqgjzqylkbwyvzyzywu.supabase.co/storage/v1/object/public/resources/code8/test1/c8.1.q11.img.png', 'c8.1.q11.img.png'),
    (v_course_id, 1, 'This road marking indicates to drivers that...', 'this lane is for the exclusive uses of buses', 'you may use this lane if you want to pickup people', 'any vehicle dropping or picking up passengers may use this lane', 'A', 'https://wzqgjzqylkbwyvzyzywu.supabase.co/storage/v1/object/public/resources/code8/test1/c8.1.q12.img.png', 'c8.1.q12.img.png'),
    (v_course_id, 1, 'This sign indicates to the driver that there...', 'are obstructions to the road for 1 km', 'are obstructions to the road 1 km ahead that affect the traffic movement', 'are road works within 1 km', 'B', 'https://wzqgjzqylkbwyvzyzywu.supabase.co/storage/v1/object/public/resources/code8/test1/C8.1.q14.img.png', 'C8.1.q14.img.png'),
    (v_course_id, 1, 'This sign indicates to the driver of a vehicle that...', 'the minimum speed limit in the right-hand lane is temporarily 80km per hour', 'the minimum speed limit in the right-hand lane is 80km per hour', 'the maximum speed limit in the right-hand lane is 80km per hour', 'A', 'https://wzqgjzqylkbwyvzyzywu.supabase.co/storage/v1/object/public/resources/code8/test1/C8.1.q16.img.png', 'C8.1.q16.img.png'),
    (v_course_id, 1, 'Where can you come across this sign', 'Usually on the left-hand side of an ordinary road opposite an on-ramp to a freeway', 'Usually on the left-hand side of a freeway before an off-ramp', 'Usually on the left-hand side of an ordinary road a couple of metres before an on-ramp to a freeway', 'A', 'https://wzqgjzqylkbwyvzyzywu.supabase.co/storage/v1/object/public/resources/code8/test1/C8.1.q18.img.png', 'C8.1.q18.img.png'),
    (v_course_id, 1, 'This road marking warns the road user that...', 'overtaking is not allowed', 'the road will split', 'the right lane may be used by vehicles moving in opposite directions at different times', 'C', 'https://wzqgjzqylkbwyvzyzywu.supabase.co/storage/v1/object/public/resources/code8/test1/C8.1.q19.img.png', 'C8.1.q19.img.png'),
    (v_course_id, 1, 'This sign shows the driver of the vehicle that...', 'there is an alternative route at the next intersection to the right', 'the road turns to the right only', 'at the next intersection the driver must turn right', 'A', 'https://wzqgjzqylkbwyvzyzywu.supabase.co/storage/v1/object/public/resources/code8/test1/C8.1.q20.img.png', 'C8.1.q20.img.png'),
    (v_course_id, 1, 'This road sign shows you that...', 'there is a parking for motor cars there', 'you must drive there', 'the lane is reserved for motor cars', 'A', 'https://wzqgjzqylkbwyvzyzywu.supabase.co/storage/v1/object/public/resources/code8/test1/C8.1.q21.img.png', 'C8.1.q21.img.png'),
    (v_course_id, 1, 'This road marking tells you that...', 'you may never park next to the road indicated by the black arrow', 'the road is under construction', 'you may not stop next to the road over there', 'A', 'https://wzqgjzqylkbwyvzyzywu.supabase.co/storage/v1/object/public/resources/code8/test1/C8.1.q22.img.png', 'C8.1.q22.img.png'),
    (v_course_id, 1, 'This road sign shows you that...', 'the area is for motor car taxis only', 'you can drive there if you wish', 'you must drive there', 'C', 'https://wzqgjzqylkbwyvzyzywu.supabase.co/storage/v1/object/public/resources/code8/test1/C8.1.q23.img.png', 'C8.1.q23.img.png'),
    (v_course_id, 1, 'The appropriate reaction to this sign is to...', 'stop as the road is closed', 'turn around as the road ends', 'slow down and prepare to stop if necessary', 'C', 'https://wzqgjzqylkbwyvzyzywu.supabase.co/storage/v1/object/public/resources/code8/test1/C8.1.q25.img.png', 'C8.1.q25.img.png'),
    (v_course_id, 1, 'When a vehicle is travelling in the right-hand lane as shown in this sign a driver must...', 'Drive faster than or drive 50km/h', 'Drive slower than 50km/h', 'Overtake vehicles in the right hand lane that are travelling slower than 50km/h', 'A', 'https://wzqgjzqylkbwyvzyzywu.supabase.co/storage/v1/object/public/resources/code8/test1/C81.q27.img%20-%20Copy%20-%20Copy.png', 'C81.q27.img - Copy - Copy.png'),
    (v_course_id, 1, 'The road marking next to the black arrow tells you that...', 'you may not stop there between certain periods indicated by another appropriate road sign', 'you may stop adjacent to the red line', 'you may not stop there at all times', 'A', 'https://wzqgjzqylkbwyvzyzywu.supabase.co/storage/v1/object/public/resources/code8/test1/C8.1.q28.img.png', 'C8.1.q28.img.png'),
    (v_course_id, 1, 'This road marking indicates to the road user...', 'that he/she may stop there to drop off passengers', 'not to stop on the marking or cross it when overtaking', 'that the lines may be crossed in order to overtake another vehicle', 'A', 'https://wzqgjzqylkbwyvzyzywu.supabase.co/storage/v1/object/public/resources/code8/test1/C8.1.q29.img.png', 'C8.1.q29.img.png'),
    (v_course_id, 1, 'When the robot is red and the red arrow flashes to the left it shows you that...', 'you must stop behind the stop line and only proceed left if it is safe to do so even if the red light is on', 'you don''t have to stop and you may just turn left', 'you must slow down and then turn left without yielding to other traffic', 'A', 'https://wzqgjzqylkbwyvzyzywu.supabase.co/storage/v1/object/public/resources/code8/test1/C8.1.q30.img.png', 'C8.1.q30.img.png'),
    (v_course_id, 1, 'This group of signs is known as...', 'an information sign', 'a warning sign', 'a regulatory sign', 'A', 'https://wzqgjzqylkbwyvzyzywu.supabase.co/storage/v1/object/public/resources/code8/test1/C8.1.q31.img.png', 'C8.1.q31.img.png'),
    (v_course_id, 1, 'This sign shows you that...', 'taking photographs is not permitted', 'there is a photographic studio ahead', 'there is a speed camera monitoring the intersection of the traffic light', 'C', 'https://wzqgjzqylkbwyvzyzywu.supabase.co/storage/v1/object/public/resources/code8/test1/C8.1.q32.img.png', 'C8.1.q32.img.png'),
    (v_course_id, 1, 'This sign shows to drivers of vehicles that...', 'this is a parking for police vehicles', 'parking is available free of charge', 'parking is available only upon paying the fee indicated at such a parking area', 'C', 'https://wzqgjzqylkbwyvzyzywu.supabase.co/storage/v1/object/public/resources/code8/test1/C8.1.q33.img.png', 'C8.1.q33.img.png'),
    (v_course_id, 1, 'Which control is used to avoid the vehicle stalling just before coming to a complete standstill', '7', '8', '10', 'B', 'https://wzqgjzqylkbwyvzyzywu.supabase.co/storage/v1/object/public/resources/code8/test1/Controls.img.jpg', 'Controls.img.jpg'),
    (v_course_id, 1, 'Which control is used to select a gear', '6', '5', '8', 'A', 'https://wzqgjzqylkbwyvzyzywu.supabase.co/storage/v1/object/public/resources/code8/test1/Controls.img.jpg', 'Controls.img.jpg'),
    (v_course_id, 1, 'If your car is automatic you will not have control number...', '8', '2', '4', 'A', 'https://wzqgjzqylkbwyvzyzywu.supabase.co/storage/v1/object/public/resources/code8/test1/Controls.img.jpg', 'Controls.img.jpg'),
    (v_course_id, 1, 'Which control is used to avoid the vehicle stalling just before coming to a complete standstill', '10', '7', '8', 'C', 'https://wzqgjzqylkbwyvzyzywu.supabase.co/storage/v1/object/public/resources/code8/test1/Controls.img.jpg', 'Controls.img.jpg'),
    (v_course_id, 1, 'Which number is used to indicate that you wish to turn right or left', '5', '2', '1', 'A', 'https://wzqgjzqylkbwyvzyzywu.supabase.co/storage/v1/object/public/resources/code8/test1/Controls.img.jpg', 'Controls.img.jpg'),
    (v_course_id, 1, 'Which number is used to steer the vehicle', '10', '4', '3', 'B', 'https://wzqgjzqylkbwyvzyzywu.supabase.co/storage/v1/object/public/resources/code8/test1/Controls.img.jpg', 'Controls.img.jpg'),
    (v_course_id, 1, 'Which numbers are used to see behind you', '1 and 3', '7 and 8', '2 and 3', 'A', 'https://wzqgjzqylkbwyvzyzywu.supabase.co/storage/v1/object/public/resources/code8/test1/Controls.img.jpg', 'Controls.img.jpg'),
    (v_course_id, 1, 'Which number is used to stop the vehicle', '9', '7', '8', 'A', 'https://wzqgjzqylkbwyvzyzywu.supabase.co/storage/v1/object/public/resources/code8/test1/Controls.img.jpg', 'Controls.img.jpg'),
    (v_course_id, 1, 'Which number makes the vehicle accelerate', '2', '3', '10', 'C', 'https://wzqgjzqylkbwyvzyzywu.supabase.co/storage/v1/object/public/resources/code8/test1/Controls.img.jpg', 'Controls.img.jpg'),
    (v_course_id, 1, 'Which is ALLOWED when towing another vehicle? (i) a motor car tows another motor car with a rope and drives 40 km/h (ii) you tow another vehicle with a tow-bar (iii) a tractor tows a trailer with 10 passengers on it at a speed of 30 km/h SELECT THE CORRECT COMBINATION', 'All of the above are correct', '(ii) and (iii) are only correct', '(i) only is correct', 'B', NULL, NULL),
    (v_course_id, 1, 'When your licence disc has expired you are given a grace period of _____ to renew it without any penalty', '21 days', '90 days', '12 months', 'A', NULL, NULL),
    (v_course_id, 1, 'You are not allowed to stop...', 'With the front of your vehicle facing on-coming traffic', 'Next to any obstruction in the road', 'On the pavement', 'C', NULL, NULL),
    (v_course_id, 1, 'You may overtake another vehicle on the left-hand side... (i) When that vehicle is going to turn right and the road is wide enough (ii) Where the road has 2 lanes for traffic moving in the same direction (iii) If a police officer instructs you to do so SELECT THE CORRECT COMBINATION', '(ii) and (iii) only are correct', 'All of the above are correct', '(iii) only is correct', 'B', NULL, NULL),
    (v_course_id, 1, 'It is illegal when you drive and a passenger...', 'sits directly behind you when you only have a learners licence', 'fiddles with the motor radios volume knob', 'rides on the bumper of your vehicle', 'C', NULL, NULL),
    (v_course_id, 1, 'You may...', 'Drive your vehicle on the sidewalk at night', 'Leave the engine of your vehicle idling when you put petrol in it', 'Reverse your vehicle only if it is safe to do so', 'C', NULL, NULL),
    (v_course_id, 1, 'What is true with regard to seatbelts? (i) if your vehicle has seatbelts in the rear it must be worn (ii) you need not wear a seatbelt when reversing (iii) children younger than 14 years need not wear seatbelts (iv) if the front seat has a seatbelt your only passenger may not sit at the back where there is no seatbelt SELECT THE CORRECT COMBINATION', '(i) (ii) and (iv) are correct', 'Only (i) is correct', 'All of the above are correct', 'B', NULL, NULL),
    (v_course_id, 1, 'If you see that someone wants to overtake you you must... (i) Not drive faster (ii) Keep to the left as far as is safe (iii) Give hand signals to allow the person to pass safely SELECT THE CORRECT COMBINATION', '(ii) is only correct', 'Only (i) and (ii) are correct', 'All of the above are correct', 'B', NULL, NULL),
    (v_course_id, 1, 'At an intersection...', 'You can pass another vehicle waiting to turn right on its left side by going off the road', 'You can stop in it to offload passengers', 'Pedestrians who are already crossing the road when the red man signal starts showing have right of way', 'C', NULL, NULL),
    (v_course_id, 1, 'The tread pattern of your vehicles tyres may not be less than...', '0.75mm', '1.5mm', '1mm', 'C', NULL, NULL),
    (v_course_id, 1, 'You are not allowed to stop...', 'Where you are also prohibited to park', 'Opposite a vehicle where the road-way is 10m wide', '5m from a bridge', 'A', NULL, NULL),
    (v_course_id, 1, 'When you want to change lanes you must... (i) Only do it when it is safe to do so (ii) Switch on your indicators in time (iii) Use the mirrors of your vehicle SELECT THE CORRECT COMBINATION', 'Only (i) and (ii) are correct', 'Only (ii) and (iii) are correct', 'All of the above are correct', 'C', NULL, NULL),
    (v_course_id, 1, 'Unless otherwise shown by a sign the general speed limit in an urban area is...km/h', '80', '100', '60', 'C', NULL, NULL),
    (v_course_id, 1, 'What is the longest period that a vehicle may be parked on one place on a public road in urban areas', '48 hours', '24 hours', '7 days', 'B', NULL, NULL),
    (v_course_id, 1, 'When are you allowed to drive on the shoulder of a road? (i) Any time if you want to let another vehicle pass you (ii) In daytime when you want to allow another vehicle pass you and its safe (iii) When on a freeway with 4 lanes in both directions you want to drive slower than 120 km/h (iv) When you have a flat tyre and you want to park there to change it SELECT THE CORRECT COMBINATION', '(ii) and (iv) only are correct', 'All of the above are correct', '(i) (iii) and (iv) only are correct', 'A', NULL, NULL),
    (v_course_id, 1, 'The legal speed limit which you may drive...', 'Is always 120km/h outside an urban area', 'Can be determined by yourself if you look at the number of lanes the road has', 'Is shown to you by signs next to the road', 'C', NULL, NULL),
    (v_course_id, 1, 'The maximum distance between two vehicles which are been towed is...m', '2.5', '3.5', '1.8', 'A', NULL, NULL),
    (v_course_id, 1, 'The following vehicles are not allowed on a freeway', 'A tractor except when it is used in connection with construction or maintenance of the freeway', 'A vehicle driven by a learner driver', 'A vehicle used for the conveyance of school children', 'A', NULL, NULL),
    (v_course_id, 1, 'The lights of your vehicle parked on a public road between sunset and sunrise need not be kept lighted when the vehicle is parked... (i) 10m from a lighted street lamp (ii) next to the roadway of the road (iii) in a demarcated parking area SELECT THE CORRECT COMBINATION', 'Only (i) and (iii) are correct', 'Only (ii) and (iii) are correct', 'All of the above are correct', 'A', NULL, NULL),
    (v_course_id, 1, 'The furthest distance that your vehicle''s dim light may shine in front of you is...m', '100', '150', '45', 'A', NULL, NULL),
    (v_course_id, 1, 'When may you not overtake another vehicle? (i) Are nearing the top of hill (ii) Are nearing a curve (iii) Can only see 100m in front of you because of dust over the road SELECT THE CORRECT COMBINATION', '(i) and (ii) only are correct', '(i) only is correct', 'All of the above is correct', 'C', NULL, NULL),
    (v_course_id, 1, 'The licence disc of your vehicle is valid for...', '21 days', '90 days', '12 months', 'C', NULL, NULL),
    (v_course_id, 1, 'What is the longest period that a vehicle may be parked on one place on a public road outside urban areas', '48 hours', '7 days', '24 hours', 'C', NULL, NULL),
    (v_course_id, 1, 'Which rule is considered the most important RULE OF THE ROAD in South Africa', 'Keep to the left side of the road far as is safe', 'Do not exceed the speed limit', 'Always be courteous and considerate towards fellow road users', 'A', NULL, NULL),
    (v_course_id, 1, 'You may pass another vehicle on the left-hand side if it... (i) Indicates that it is going to turn right (ii) Drives on the right-hand side of a road with a shoulder were you can pass (iii) Drives in a town in the right hand lane with 2 lanes in the same direction SELECT THE CORRECT COMBINATION', 'All of the above are correct', '(i) and (iii) only are correct', '(i) only is correct', 'B', NULL, NULL),
    (v_course_id, 1, 'If you only have a learners licence for a light motor vehicle... (i) there must be someone with you in the vehicle with the same driving licence (ii) you are not allowed to drive on a freeway (iii) no passengers are allowed with you in the vehicle SELECT THE CORRECT COMBINATION', 'Only (i) is correct', 'All of the above are correct', 'Only (i) and (iii) are correct', 'A', NULL, NULL);

  RAISE NOTICE 'Inserted % questions for course_id=%', 62, v_course_id;
END $$;