-- ============================================================
-- K53 Learner's Licence Platform — Full Database Schema
-- Run this in: Supabase Dashboard → SQL Editor → New Query
-- ============================================================

-- ── 1. COURSES ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS courses (
  id          bigint generated by default as identity primary key,
  title       text not null,
  description text,
  code        text unique,          -- e.g. 'code8', 'code10'
  created_at  timestamptz default now()
);

-- Seed: Code 8 course
INSERT INTO courses (title, description, code)
VALUES (
  'Code 8 — Light Motor Vehicle',
  'Study material and quizzes for the Code 8 K53 learner''s licence test covering road signs, vehicle controls, and rules of the road.',
  'code8'
)
ON CONFLICT (code) DO NOTHING;

-- ── 2. QUIZ QUESTIONS ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS quiz_questions (
  id             bigint generated by default as identity primary key,
  course_id      bigint references courses(id) on delete cascade,
  test_number    int8 not null default 1,
  question       text,
  option_a       text,
  option_b       text,
  option_c       text,
  option_d       text,
  correct_answer text check (correct_answer in ('A','B','C','D')),
  image_url      text,              -- Supabase Storage public URL
  image_ref      text,              -- e.g. 'C81.q1.img' or 'controls-diagram'
  created_at     timestamptz default now()
);

-- Add columns if table already exists (idempotent)
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='quiz_questions' AND column_name='test_number') THEN
    ALTER TABLE quiz_questions ADD COLUMN test_number int8 not null default 1;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='quiz_questions' AND column_name='image_url') THEN
    ALTER TABLE quiz_questions ADD COLUMN image_url text;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='quiz_questions' AND column_name='image_ref') THEN
    ALTER TABLE quiz_questions ADD COLUMN image_ref text;
  END IF;
END $$;

-- ── 3. QUIZ ATTEMPTS ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS quiz_attempts (
  id               bigint generated by default as identity primary key,
  user_id          uuid references auth.users(id) on delete cascade,
  course_id        bigint references courses(id) on delete cascade,
  test_number      int8 not null default 1,
  score            int not null default 0,
  total_questions  int not null default 0,
  passed           boolean generated always as (score::float / nullif(total_questions,0) >= 0.75) stored,
  completed_at     timestamptz,
  created_at       timestamptz default now()
);

-- ── 4. USER ANSWERS ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS user_answers (
  id              bigint generated by default as identity primary key,
  attempt_id      bigint references quiz_attempts(id) on delete cascade,
  question_id     bigint references quiz_questions(id) on delete cascade,
  selected_answer text check (selected_answer in ('A','B','C')),
  is_correct      boolean,
  created_at      timestamptz default now()
);

-- ── 5. ROW-LEVEL SECURITY ────────────────────────────────────

-- courses: public read
ALTER TABLE courses ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "courses_public_read" ON courses;
CREATE POLICY "courses_public_read"
  ON courses FOR SELECT USING (true);

-- quiz_questions: public read
ALTER TABLE quiz_questions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "questions_public_read" ON quiz_questions;
CREATE POLICY "questions_public_read"
  ON quiz_questions FOR SELECT USING (true);

-- quiz_attempts: users manage their own rows
ALTER TABLE quiz_attempts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "attempts_own_rows" ON quiz_attempts;
CREATE POLICY "attempts_own_rows"
  ON quiz_attempts FOR ALL
  USING  (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- user_answers: users manage their own rows via attempt ownership
ALTER TABLE user_answers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "answers_own_rows" ON user_answers;
CREATE POLICY "answers_own_rows"
  ON user_answers FOR ALL
  USING  (attempt_id IN (SELECT id FROM quiz_attempts WHERE user_id = auth.uid()))
  WITH CHECK (attempt_id IN (SELECT id FROM quiz_attempts WHERE user_id = auth.uid()));

-- ── 6. HELPFUL INDEXES ───────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_questions_course_test
  ON quiz_questions(course_id, test_number);

CREATE INDEX IF NOT EXISTS idx_attempts_user
  ON quiz_attempts(user_id);

CREATE INDEX IF NOT EXISTS idx_answers_attempt
  ON user_answers(attempt_id);
